### PR TITLE
Add Amazon Linux 2 in repo.pp

### PR DESCRIPTION
**Pull request by lduriez**

### CODE REVIEW

**Comment by lduriez** [comment]
I don't have any idea of why the checks go wrong.
Can I have some help ? (I really need amazon linux 2 working for that)

Fluentd doc for Amazon Linux installation
https://docs.fluentd.org/installation/install-by-rpm#amazon-linux

**Comment by lduriez** [comment]
I guess it's the repo_spec.rb, it tried something but doesn't seems to work, and I have a lack of knowledge here.

**Comment by nmaludy** [comment]
@lduriez sorry i didn't get notified of this PR, let's see if we can get you going... what derivative is Amazon Linux, is it Red Hat?

**Review by nmaludy — APPROVED** [review]
@lduriez thanks so much for the contribution! next time feel free to @ mention me and i'll be sure to review this sooner!

**Comment by nmaludy** [comment]
@lduriez FYI this change is now available on the forge in version `1.1.0` https://forge.puppet.com/modules/encore/fluentd

**Comment by lduriez** [comment]
Thanks :-)

**Pull request merged**
