### PR TITLE
Don't prepend @ when plugin_type is system

### PR DESCRIPTION
**Pull request by synical**
I've been using this module recently and I noticed that if I set the `log_level` parameter for system config it wouldn't have an effect on the log level of system logs.

Looking through the docs it seems that config at the system level should not be prepended with an `@`, as this is for overriding configuration at the plugin level. For example: https://docs.fluentd.org/configuration/plugin-common-parameters#log_level.

This PR updates `config.rb` so that it does not prefix any parameters at the `system` level with `@`.

I couldn't find any other way to set system config so went with the approach of updating the `config.rb` code. Not particularly experienced with Ruby, so am happy to update the implementation (or use some other mechanism for configuring the system if I'm missing something).

### CODE REVIEW

**Review by nmaludy — CHANGES_REQUESTED** [review]
@synical these changes look good, can you please add an entry to CHANGELOG.md under the Development section?

Thanks,
Nick

**Comment by synical** [comment]
@nmaludy sure, updated as requested.

**Comment by nmaludy** [comment]
I'm looking into Windows unit test issues. It does look like you have a syntax gotcha found by Rubocop https://github.com/EncoreTechnologies/puppet-fluentd/runs/4081376851?check_suite_focus=true

**Comment by synical** [comment]
Ah yes, pushed a commit to make Rubocop happy.

**Review by nmaludy — APPROVED** [review]

**Comment by nmaludy** [comment]
@synical thanks for the PR, v1.2.0 is live on the forge https://forge.puppet.com/modules/encore/fluentd

**Pull request merged**
